### ISSUE TITLE
OSX : Errors prevented startup: While loading plugin `compileScss` from package `fourseven:scss`:

### ISSUE THREAD

**Issue by lc3t35** [SpaceTalk/SpaceTalk#117]
On OSX 10.8.5, 

```
=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  

   While loading plugin `compileScss` from package `fourseven:scss`:
   module.js:356:32:
   dlopen(/Users/laurent/.meteor/packages/fourseven_scss/.3.1.1.k14kpn++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/vendor/darwin-x64-11/binding.node,
   1): Symbol not found: __ZNSt12out_of_rangeD1Ev
   Referenced from:
   /Users/laurent/.meteor/packages/fourseven_scss/.3.1.1.k14kpn++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/vendor/darwin-x64-11/binding.node
   Expected in: /usr/lib/libstdc++.6.dylib
   in
   /Users/laurent/.meteor/packages/fourseven_scss/.3.1.1.k14kpn++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/vendor/darwin-x64-11/binding.node
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (/Users/laurent/.meteor/packages/fourseven_scss/.3.1.1.k14kpn++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/lib/index.js:16:15)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object._.extend.Npm.require
   (/Users/laurent/.meteor/packages/meteor-tool/.1.1.3.1mvydc8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:1341:22)
   at Package (packages/compileScss/plugin/compile-scss.js:2:1)
   at <runJavaScript-30>:146:4
   at <runJavaScript-30>:153:3
=> Your application has errors. Waiting for file change.
```

Submitted here -> https://github.com/fourseven/meteor-scss/issues/95

**Comment by jmellows** [comment]
i am also getting the same, is there a work around?
